# Generated by Django 5.2.3 on 2025-07-28 18:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإنجاز')),
                ('description', models.TextField(verbose_name='وصف الإنجاز')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='أيقونة الإنجاز')),
                ('unlocked', models.BooleanField(default=False, verbose_name='تم الفتح')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الفتح')),
                ('required_days', models.IntegerField(blank=True, null=True, verbose_name='الأيام المطلوبة')),
                ('type', models.CharField(choices=[('streak', 'Streak'), ('milestone', 'Milestone'), ('special', 'Special')], max_length=50, verbose_name='نوع الإنجاز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_list', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إنجاز',
                'verbose_name_plural': 'إنجازات',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='المحتوى')),
                ('entry_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ اليومية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_relapse', models.BooleanField(default=False, verbose_name='هل هي نكسة؟')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'يومية',
                'verbose_name_plural': 'يوميات',
                'ordering': ['-entry_date'],
                'unique_together': {('user', 'entry_date')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.CharField(max_length=100, verbose_name='معرف الإنجاز')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفتح')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إنجاز المستخدم',
                'verbose_name_plural': 'إنجازات المستخدمين',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement_id')},
            },
        ),
    ]
