# Generated by Django 5.2.3 on 2025-07-22 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإنجاز')),
                ('description', models.TextField(verbose_name='وصف الإنجاز')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='أيقونة الإنجاز')),
                ('unlocked', models.BooleanField(default=False, verbose_name='تم الفتح')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الفتح')),
                ('required_days', models.IntegerField(blank=True, null=True, verbose_name='الأيام المطلوبة')),
                ('type', models.CharField(choices=[('streak', 'Streak'), ('milestone', 'Milestone'), ('special', 'Special')], max_length=50, verbose_name='نوع الإنجاز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_list', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إنجاز',
                'verbose_name_plural': 'إنجازات',
                'ordering': ['-unlocked_at'],
            },
        ),
    ]
